### ISSUE TITLE
Propuesta de diseño

### ISSUE THREAD

**Issue by penserbjorne** [LIDSOL/sitio-web-lidsol#1]
Para darle continuidad a lo trabajado en el laboratorio, todos aquellos que quieran dar una **propuesta de diseño** para el sitio pueden hacerlo libremente _en este issue_.

Para darle buen paso, propongo que la votación de diseños dure a lo mucho una semana a partir de hoy **(del 27/12/2016 al 03/01/2016) con cierre a las 20 hrs**.

![Estructura del sitio.](https://cloud.githubusercontent.com/assets/8706953/21511130/3ef26dae-cc62-11e6-98d4-52521b18b100.png)

Cualquier **duda** o comentario sobre el tema puede tocarse de manera **resumida** y concisa **en este issue**, o si desean **algo mas extenso** y expresivo **en el grupo de telegram**.

@Penserbjorne

**Comment by penserbjorne** [comment]
Me gustaria proponer [este tema](https://github.com/penserbjorne/darcli) , me gusto bastante el diseño, ademas de que esta hecho con Jekyll, creo que podria cumplir con todas las necesidades salvo la vista adaptativa para las cosas de calendarios/cursos, y la parte movil, al parecer no es resposivo completamente, pero podriamos tomarlo como base.

[Live preview](https://gjuniioor.github.io/darcli/)

**Comment by marc019** [comment]
Propuesta 2:
A mi me late la idea de una single page. Creo que se puede adecuar bien a la arquitectura que tenemos contemplada para el sitio.
Entre alguna de las opciones que me pareció novedosa es la siguiente:
http://netlab.pro/en

Obviamente con ese toque lidsolero y nuestro propio estilo.

**Comment by emilio1625** [comment]
Las single page son malas para el SEO, además que que en general son lentas y desesperantes en su carga, creo que seria mejor una web estática que los robots puedan analizar.
Sin embargo me agrada bastante esa web, podríamos adaptar nuestro diseño a eso, también me agrada la de @penserbjorne, pero si le falta bastante para ser responsiva, al menos de lo que he visto

**Comment by emilio1625** [comment]
Propuesta 3:
En general soy muy conservador en cuanto al diseño web, no me agradan las paginas cargadas de JS, y me agradan los diseños minimalistas, propongo crear una pagina similar a la de ese blog, solo el diseño.
En la parte técnica propongo trabajar con symfony, un framework PHP bastante profesional, bootstrap, o tal vez foundation, que son frameworks de CSS que se llevan bien con symfony, jQuery, y una librería ligera y bastante agradable desde mi punto de vista, llamada Reactive.JS (no confundir con react.JS de facebook) que podría ser útil si en algún momento queremos introducir contenido dinámico en la pagina, los creadores de reactive son los desarrolladores del sitio web de The Guardian
http://www.muylinux.com
https://www.theguardian.com/international

**Comment by Eysvafa** [comment]
A mi me gusto mucho visualmente la propuesta de @marc019 pero después de probarla en escritorio (primero la probe en móvil) me pareció que sus efectos son un tanto mareadores. Me quedo con la propuesta 3, porque creo que le podemos dar pesonalidad con los colores que usemos y porque se me hace la más practica para lo que recuerdo que dijimos que queriamos hacer (:
Feliz Año :dango:

**Comment by penserbjorne** [comment]
Dado que la propuesta es sobre diseño, yo voto por la propuesta 2 ( de @marc019 ), mas que nada ya que solo estamos buscando un estilo, el hecho de trabajar con Jekyll automaticamente le dara una vista similar a la que propone @emilio1625 a la parte de blog, la parte estatica se puede crear facilmente con Jekyll tambien, asi que no hay píerde.

**Comment by chipotles714** [comment]
Yo despues de meditar y meterme varias veces a los enlaces de las propuestas voto por la segunda propuesta la de @marc019 porque siento que eso dará un toque diferente y se puede tener un buen primer acercamiento con una pagina que se vea un poco distinta a las demás :)

**Comment by emilio1625** [comment]
Voto por la propuesta 3

**Comment by emilio1625** [comment]
La propuesta 2 perdon me equivoque xDD

**Comment by penserbjorne** [comment]
Dados los votos emitidos, gano la propuesta de @marc019 .

Se cerrara el issue. :)
