### ISSUE TITLE
Creacion de contenido estatico y herramientas para el sitio.

### ISSUE THREAD

**Issue by penserbjorne** [LIDSOL/sitio-web-lidsol#2]
Para darle continuidad a lo trabajado en el laboratorio, todos aquellos que quieran **colaborar en el desarrollo del sitio** pueden anotarse libremente _en este issue_.

Para darle buen paso, propongo que la lista de voluntarios quede abierta a lo mucho cinco días a partir de mañana **(del 01/05/2016 al 09/01/2016) con cierre a las 20 hrs**.

La lista de contenido a generar es la que viene en la imagen, en general:
- Información General
- Actividades
- Blog
- Wiki

También es necesario hacer una propuesta de las herramientas o diseño/implementación para cada sección. 
- Todas las secciones deben cumplir con el estilo propuesto por @marc019 en el issue anterior.
- La sección de _Información General_ se usara a la par para abrir un tema en Wikipedia. Para el sitio se usara Jekyll, pero basta con generar la información estática y pasarse a los que tomen _Actividades_.
- La sección de _Actividades_ necesitara una implementación dinámica, por lo que se aceptan propuestas libres de herramientas :) .
- La sección del blog se cubriría con Jekyll como ya se había dicho, por lo que quienes decidan tomar la tarea de el desarrollo del blog deberán cubrir tanto el uso de Jekyll. También se encargaran de añadir la información estática de _Información General_.
- La Wiki se instalara en el servidor, por lo que tendrán que trabajar de entrada conmigo o con @emilio1625 , la wiki se ira actualizando conforme los proyectos avancen y se vaya requiriendo.

![Estructura del sitio.](https://cloud.githubusercontent.com/assets/8706953/21511130/3ef26dae-cc62-11e6-98d4-52521b18b100.png)

Cualquier **duda** o comentario sobre el tema puede tocarse de manera **resumida** y concisa **en este issue**, o si desean **algo mas extenso** y expresivo **en el grupo de telegram**.

@Penserbjorne

**Comment by emilio1625** [comment]
Propuesta 1:
Para el backend:
Lenguajes PHP 7, Twig
* Uso de un estilo de desarrollo modelo vista controlador para el servidor web
* Gestion de paquetes de php con composer https://getcomposer.org/
* Uso del framework Symfony https://es.wikipedia.org/wiki/Symfony https://symfony.com/
El framework incluye las siguientes herramientas:
* Doctrine para la parte del modelo y base de datos, es una capa de abstraccion que nos permite usar objetos que son mapeados a tablas en la base de datos http://www.doctrine-project.org/
* Twig para la vista, la creacion de plantillas y paginas web dinámicas, permite el reuso de codigo mediante la "herencia" entre plantillas http://twig.sensiolabs.org/
* Symfony que se encarga de la parte del controlador, tiene la estructura de un microkernel que puede ser extendido mediante modulos de carga dinamica, todo el sistema se basa en la idea de recibir un objeto Request y devolver un objeto Response.
En general yo he trabajado la mayor parte del framework y lo encuentro muy comodo de trabajar y muy rapido, facil de depurar y de integrar modulos que ademas son fáciles de extender
Hay disponibles modulos para usar Markdown para la creacion de paginas estaticas que ademas se integra a Twig, y modulos para integrar mediawiki (la plataforma wiki de wikimedia).
Alternativamente en symfony no seria dificil crear nuestra propia plataforma de wikis

Para el frontend:
Lenguajes CoffeeScript JS, SCSS, HTML5
* Usar Reactive.JS para el dinamismo de lado del servidor. http://www.ractivejs.org/
* Para todas aquellas funciones mas sencllas propongo el uso de Coffescript, es un pequeño lenguaje que se compila a javascript y ahorra mucho tiempo al escribir scripts en general. http://coffeescript.org/
* Boostrap 4 para el estilo de la pagina, aunque el proyecto esta marcado como en version alpha se espera que para este año sea lanzado, en el tiempo que he trabajado con el, no he encontrado problemas. https://v4-alpha.getbootstrap.com/
Ademas no crear el estilo con css sino con scss, es un lenguaje de programacion que compila en css3 que nos permitira crear estilos de forma mas sencilla y rapida, http://sass-lang.com/
Symfony, además integra herramientas para el manejo de estos "assets" de forma facil con Assetic
Otra alternativa seria mantener estos aparte como un modulo de node.js y manejarlos mediante Bower y Gulp https://bower.io/ http://gulpjs.com/

Finalmente para el deploy propongo utilizar contenedores de linux que pemriten tener una capa de seguridad extra a nuestro sistema, en este aspecto propongo el uso de docker, aunque podriamos dicutir el uso de alternativas como systemd nspawn

**Comment by penserbjorne** [comment]
@emilio1625 ok, pero y todo eso aplicada ... para?

Ya se habia definido algo, y el issue sigue con lo que se planteo desde un principio, so, cual seria la aplicacion de todo lo que comentas? o por donde va el asunto?

**Comment by penserbjorne** [comment]
Dada la poca participación en este issue,  se extenderá el tiempo para comentar dos días mas,  el cierre sera el Miércoles  11/01/2016 a las 20 hrs. 

En caso de que no haya interés por parte de mas miembros del laboratorio para participar en esta actividad, se replantearan las tecnologías propuestas en el laboratorio y se dará paso a usar las tecnologias que comenta @emilio1625 siempre y cuando se haga una propuesta mas estructurada y especifica de que se desarrollara y que se usara para el desarrollo,  debe respetar por lo menos la estructura definida en el laboratorio y el estilo votado anteriormente,  cualquier modulo/seccion extra se trabajara posteriormente. 

En caso de que nadie mas vuelva a mostrar interés en la actividad (incluyendo a Emilio) tomare el desarrollo del sitio inmediatamente por mi cuenta dado que es una actividad que se dejo pendiente desde Diciembre y que urge.

En cualquier caso, cualquier persona interesada en incorporarse al desarrollo del sitio deberá solicitarlo mediante un issue o en el grupo.

**Comment by penserbjorne** [comment]
Cualquier persona interesada en incorporarse al desarrollo del sitio deberá solicitarlo mediante un issue o en el grupo de telegram.
